import { StyleSheet, Dimensions } from "react-native";

export const createStyles = () =>
  StyleSheet.create({
    modal: {
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
    },
    modalSheet: {
      width: Dimensions.get("screen").width * 0.8,
      backgroundColor: "#F9F9F9",
      paddingTop: 65,
      paddingBottom: 85,
      alignItems: "center",
      borderRadius: 15,
      borderColor: "#A2A2A2",
      borderWidth: 0.5,
      zIndex: 1000,
      shadowColor: "#A2A2A2",
      shadowOpacity: 0.5,
      shadowOffset: { width: 3, height: 3 },
    },
    modalTitle: {
      top: 15,
      alignSelf: "center",
      position: "absolute",
      color: "#515151",
      fontSize: 25,
      fontWeight: "600",
    },
    image: {
      width: 150,
      height: 150,
      borderRadius: 75,
      borderColor: "#000",
      borderWidth: 0.5,
    },
    plusButton: {
      width: 48,
      height: 60,
      backgroundColor: "#000",
      borderColor: "#FFF",
      borderRadius: 8,
      borderWidth: 1,
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      bottom: 10,
      right: 10,
    },
    labelText: {
      marginTop: 15,
      fontSize: 20,
      fontWeight: "600",
    },
    divider: {
      width: "80%",
      borderBottomWidth: 0.5,
      borderBottomColor: "#515151",
      marginVertical: 15,
    },
    buttonsContainer: {
      width: "85%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    addFriendButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#E8E8E8",
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 10,
      height: 48,
      gap: 10,
    },
    addFriendButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#000",
    },
    addFriendContainer: {
      width: "85%",
      backgroundColor: "#FFF",
      padding: 15,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    addFriendTitle: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 10,
      color: "#333",
    },
    friendCodeInput: {
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 16,
      marginBottom: 12,
      backgroundColor: "#FAFAFA",
    },
    addFriendButtons: {
      flexDirection: "row",
      gap: 10,
    },
    friendButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 8,
      alignItems: "center",
    },
    cancelButton: {
      backgroundColor: "#F0F0F0",
    },
    cancelButtonText: {
      color: "#666",
      fontWeight: "600",
    },
    confirmButton: {
      backgroundColor: "#000",
    },
    confirmButtonText: {
      color: "#FFF",
      fontWeight: "600",
    },
    saveLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: "#000",
    },
    saveButton: {
      flex: 1,
      height: 48,
      borderRadius: 10,
      borderColor: "#A2A2A2",
      borderWidth: 0.5,
      backgroundColor: "#C2C2C2",
      alignItems: "center",
      justifyContent: "center",
    },
  });
