import { StyleSheet, Dimensions } from "react-native";
import { colors } from "@styles/theme";

export const createStyles = () =>
  StyleSheet.create({
    modal: {
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
    },
    modalSheet: {
      width: Dimensions.get("screen").width * 0.8,
      backgroundColor: colors.backgroundSecondary,
      paddingTop: 65,
      paddingBottom: 85,
      alignItems: "center",
      borderRadius: 15,
      borderColor: colors.border,
      borderWidth: 0.5,
      zIndex: 1000,
      shadowColor: colors.black,
      shadowOpacity: 0.5,
      shadowOffset: { width: 3, height: 3 },
    },
    modalTitle: {
      top: 15,
      alignSelf: "center",
      position: "absolute",
      color: colors.text,
      fontSize: 25,
      fontWeight: "600",
    },
    image: {
      width: 150,
      height: 150,
      borderRadius: 75,
      borderColor: colors.border,
      borderWidth: 0.5,
    },
    plusButton: {
      width: 48,
      height: 60,
      backgroundColor: colors.primary,
      borderColor: colors.text,
      borderRadius: 8,
      borderWidth: 1,
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      bottom: 10,
      right: 10,
    },
    labelText: {
      marginTop: 15,
      fontSize: 20,
      fontWeight: "600",
      color: colors.text,
    },
    divider: {
      width: "80%",
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      marginVertical: 15,
    },
    saveLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    saveButton: {
      width: "85%",
      height: 48,
      borderRadius: 10,
      borderColor: colors.border,
      borderWidth: 0.5,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
  });
