import { StyleSheet, Platform } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  wrapper: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 4,
  },
  wrapperIncoming: {
    justifyContent: "flex-start",
  },
  wrapperOutgoing: {
    justifyContent: "flex-end",
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  container: {
    flex: 1,
    marginHorizontal: 8,
    padding: 12,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
    minWidth: 200,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  leftHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  readStatusContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
  },
  readIcon: {
    color: colors.textTertiary,
  },
  readIconActive: {
    color: colors.success,
  },
  separator: {
    width: 1,
    height: 16,
    backgroundColor: colors.border,
  },
  timestampContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  timestampIcon: {
    color: colors.textTertiary,
  },
  timestamp: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  durationBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.backgroundTertiary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  durationIcon: {
    color: colors.textSecondary,
  },
  durationText: {
    fontSize: 12,
    color: colors.text,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  playContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 12,
  },
  button: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.backgroundTertiary,
    borderWidth: 2,
    borderColor: colors.borderDark,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  buttonActive: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  sliderContainer: {
    flex: 1,
    position: "relative",
  },
  slider: {
    flex: 1,
    height: 40,
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(10, 26, 18, 0.8)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
  },
  loadingText: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 2,
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timeLabel: {
    fontSize: 11,
    color: colors.textTertiary,
    fontWeight: "500",
  },
  timeText: {
    fontSize: 12,
    color: colors.text,
    fontWeight: "600",
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  playingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 10,
  },
  playingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.success,
  },
  playingText: {
    fontSize: 10,
    color: colors.success,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
});
